# Generated by Django 3.1.3 on 2020-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20201205_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='response',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
