# Generated by Django 3.1.3 on 2020-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_link_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='resp_text',
            field=models.CharField(blank=True, max_length=100000000),
        ),
    ]
