# Generated by Django 3.1.3 on 2020-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_link_resp_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='resp_text',
            field=models.CharField(blank=True, default='', max_length=100000000),
        ),
    ]
