# Generated by Django 3.1.3 on 2020-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20201205_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='finish_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
