# Generated by Django 3.1.3 on 2021-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_link_finish_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='error',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='link',
            name='last_check_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
