# Generated by Django 3.1.3 on 2021-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20210220_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_check_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
