# Generated by Django 3.1.3 on 2021-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20210220_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='in_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
